-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Hostiteľ: 127.0.0.1
-- Čas generovania: Út 25.Dec 2018, 12:35
-- Verzia serveru: 10.1.37-MariaDB
-- Verzia PHP: 7.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Databáza: `bluray`
--

-- --------------------------------------------------------

--
-- Štruktúra tabuľky pre tabuľku `film`
--

CREATE TABLE `film` (
  `id` int(11) NOT NULL,
  `zaner` varchar(30) CHARACTER SET utf8 COLLATE utf8_czech_ci NOT NULL,
  `nazov` varchar(50) CHARACTER SET utf8 COLLATE utf8_czech_ci NOT NULL,
  `cena` decimal(10,2) NOT NULL,
  `rok` int(5) NOT NULL,
  `popis` varchar(5000) CHARACTER SET utf8 COLLATE utf8_czech_ci NOT NULL,
  `pocet` int(5) NOT NULL,
  `obrazok` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Sťahujem dáta pre tabuľku `film`
--

INSERT INTO `film` (`id`, `zaner`, `nazov`, `cena`, `rok`, `popis`, `pocet`, `obrazok`) VALUES
(1, 'Akčný', 'Mad Max: Zbesilá cesta', '14.99', 2015, 'Šílený Max, pronásledovaný svou pohnutou minulostí, je přesvědčen, že jediný způsob jak přežít, je vydat se na osamělou pouť. Narazí však na skupinu prchající pustinou ve vyzbrojeném obrněném vozidle, v jejímž čele stojí elitní Imperator Furiosa. Citadelu, odkud prchají, tyranizuje Immortan Joe, kterému kdosi odcizil něco nenahraditelného. Rozzuřený vojenský vůdce svolá všechny své gangy a ve vysokooktanové silniční válce nemilosrdně pronásleduje prchající rebely.', 5, 0),
(2, 'Akčný', 'Plán úteku', '17.95', 2013, 'Ray Breslin (Sylvester Stallone) je útěkář na objednávku. Živí se totiž jako expert na infrastrukturu vězeňských zařízení. Nechává se v nich zavírat a hledá skuliny v zabezpečovacích systémech, které jsou pak následně na základě jeho analýz  - a efektních útěků - odstraňovány a zdokonalovány. Nyní nastupuje výkon trestu k nové zakázce, ale ouha: vězeňský komplex, ve kterém se ocitl, byl kompletně postaven na základě jeho dosavadních poznatků a připomínek k zabezpečení věznic. Ty Ray před časem vydal knižně a pro tyranského ředitele tohoto „nápravně výchovného zařízení\" se jeho manuál stal doslova biblí. Ray se tak ocitá ve své vlastní dokonalé pasti. Nikdo navíc neví o tom, že by byl něco jiného než řadový vězeň, takže propustka na svobodu po dobře odvedené práci jaksi chybí... Po obvyklých počátečních neshodách se Rayovým parťákem v novém „domově\" stává místní vězeňský boss - Emil Rottmayer (Arnold Schwarzenegger), který si zde odpykává trest za kyber-terorismus. A jemu se ve vězení moc nelíbí. Ale kdo jiný, než tihle dva chlápci by se měl dostat přes Rayovo bezchybné zabezpečovací systémy a celou armádu dozorců pod vedením fanatického ředitele? A je to, že se oba ocitli v této bezvýchodné situaci, opravdu jen nedorozumění a shoda náhod nebo něčí pečlivě promyšlený plán?', 3, 1),
(3, 'Akčný', 'Mission: Impossible - Fallout', '19.99', 2018, 'Ethan Hunt si vždycky vybíral nesplnitelné mise. Pokaždé v nich uspěl, okolnostem navzdory. Na začátku tohoto příběhu však čelí úplně nové situaci. Něco se pokazilo, past nesklapla a vinou jeho selhání se ocitnou ve smrtelném ohrožení vybraná světová velkoměsta. Ethan je přesvědčen, že pouze on se svým týmem dokáže tragickou chybu napravit. Je však sám, kdo si to myslí. Do hry vstupují další hráči, kteří mu možná pomáhají, ale možná také sledují své vlastní zájmy, které jsou v rozporu s těmi Ethanovými. Rozdělení na kladné a záporné hrdiny nebude tentokrát vůbec jednoduché. V pozadí navíc čím dál rychleji utíká čas vstříc momentu, který dramaticky změní mapu světa.', 2, 2),
(4, 'Akčný', 'Sicario 2: Soldado', '17.95', 2018, 'Sicario 2: Soldado otevírá novou kapitolu filmové série Sicario. V drogové válce neplatí žádná pravidla – a když kartely začaly převádět teroristy přes americké hranice, federální agent Matt Graver (Josh Brolin) vyzve tajemného Alejandra (Benicio Del Toro), kterému hlavoun kartelu vyvraždil rodinu, aby všemi prostředky, včetně těch nezákonných, válku eskaloval. Aby rozpoutal válku, unese Alejandro hlavounovu dceru – ale když se z dívky stane vedlejší oběť konfliktu, její osud tyto dva muže rozdělí, protože zpochybní vše, za co bojují.', 1, 3),
(5, 'Akčný', 'Americký zabijak', '8.99', 2017, 'Americký zabiják mapuje vzestup Mitche Rappa (Dylan O\'Brien), nováčka CIA pro „černé operace“, pod velením veterána studené války Stana Hurleyho (Michael Keaton). Společně mají za úkol vyšetřit vlnu na první pohled náhodných útoků na vojenské i civilní cíle. Když naleznou určitý vzorec, musí se vydat na misi s cílem zneškodnit tajemného agenta (Taylor Kitsch), jehož touha po osobní i profesionální pomstě může mít katastrofální následky.', 6, 4),
(6, 'Akčný', 'Mrakodrap', '18.43', 2018, 'Perla je nejvyšší a zároveň nejlépe zabezpečená budova na světě. Přesto její majitelé najmou velezkušeného bezpečnostního experta Willa Sawyera (Dwayne Johnson), aby to oficiálně potvrdil. Jenže pak začne v budově hořet a o technickou závadu se rozhodně nejedná. Will, coby bývalý šéf týmu FBI, který se specializoval na záchranu rukojmích, zažil už leccos, ale tohle je přece jen silná káva. Požár se rychle šíří a Will zjistí, že právě on je podle policie odpovědný za jeho založení. I když se zrovna pohybuje mimo budovu, bude muset rychle dovnitř, protože v jednom z nejvyšších pater je uvězněna jeho žena (Neve Campbell) se dvěma dětmi. A to stále ještě není všechno, v mrakodrapu se pohybuje ozbrojený gang, se kterým se bude muset Will taky vypořádat, pokud chce své blízké zachránit. Ještě jsme zapomněli zmínit, že po vážném zranění z minulosti má jednu nohu umělou a že jediná cesta do domu v plamenech vede přes vedle stojící jeřáb, z jehož ramene ve výšce několika desítek metrů bude muset přeskočit', 9, 5),
(7, 'Akčný', 'Tomb Raider', '17.45', 2018, 'Laře Croft (Alicia Vikander) je 21 let a právě zdědila obrovské obchodní impérium. Její otec, bohatý šlechtic a známý dobrodruh, Lord Richard Croft (Dominic West), zmizel beze stopy před sedmi lety, když byla ještě dítě. Od té doby se marně snaží najít nějaký smysl svého života. Když si přečte záhadný vzkaz, který jí otec zanechal, rozhodne se opustit Londýn a vyrazit do neznáma, aby přišla na to, co se jejímu otci doopravdy stalo. Vydá se po jeho stopách hledat legendární hrobku na mýtickém ostrově někde poblíž japonského pobřeží. Tato mise ale nebude jednoduchá – už jen dostat se na záhadný ostrov stojí Laru velké úsilí. Loď, která ji měla dopravit na pevninu ztroskotá v silné bouři a Lara se ocitá sama uprostřed neznáma, vybavená jen ostrým nožem, pevnou vírou a vlastní tvrdohlavostí. Pokud se jí podaří překonat své vlastní limity a přežít toto nebezpečné dobrodružství, stane se z ní skutečný Tomb Raider.', 4, 6),
(8, 'Akčný', 'RED 2', '12.24', 2013, 'Nabitá akční komedie RED 2 je pokračováním celosvětově úspěšného filmu o bývalém agentovi CIA, který stále leží někomu v žaludku. Frank Moses dává znovu dohromady svůj svérázný tým elitních tajných agentů. Jejich prvním úkolem je přežít a hned tím druhým je vypátrat ztracenou smrtící zbraň příští generace, která může změnit rozložení sil ve světě. Budou muset odolat hordám nemilosrdných zabijáků, teroristů a mocichtivých vládních úředníků, toužících vyzkoušet si technologicky vyspělou superzbraň. Mise zavede Franka a ostatní RED do Londýna, Paříže a Moskvy. Jejich nepřátelé mají palební i početní převahu, navíc mají Frank a ostatní problémy i tak trochu sami se sebou. Chtějí-li agenti zachránit svět a zůstat přitom na živu, nezbývá jim nic jiného, než se spolehnout na svou vynalézavost a důvtip, na dovednosti ze staré školy. A na trochu toho dynamitu.', 2, 7),
(9, 'Akčný', 'John Wick 2', '7.59', 2017, 'V pokračování úspěšného akčního thrilleru z roku 2014 přinutí legendárního Johna Wicka (Keanu Reeves) k návratu ze zabijáckého důchodu jeho bývalý spolupracovník, který se pomocí intrik snaží převzít kontrolu nad tajemným mezinárodním sdružením nájemných zabijáků. Krevní přísaha Johna zavazuje, aby mu pomohl, a tak se vypraví do Říma, kde se utká s několika nejnebezpečnějšími zabijáky na světě.', 4, 8),
(10, 'Akčný', ' Krvavý šport', '7.10', 1988, 'Akční film z roku 1987, přímo nabitý ukázkami nejrůznějších asijských bojových umění, se stal odrazovým můstkem v kariéře Jeana-Clauda Van Damma. Do té doby neznámý Belgičan se díky němu dostal do povědomí diváků - a také producentů, kteří ho začali obsazovat. V tomto snímku si fanouškové žánru jistě vychutnají i výkon jednoho z nejpopulárnějších \"záporáků\" hongkongských arén Bola Yeunga, jenž představuje hrdinova zákeřného protivníka.\r\nMálokdo ovšem také ví, že Krvavý sport je o životě a začátcích skutečného \"bojového umělce\" Franka Duxe (čti ďuks), jenž se s konečnými výsledky svých soubojů stal legendou bojového umění (56 knockoutů a 300 bodových vítězství). Dokonce Dux sám dohlížel na bojovou choreografii filmu.', 6, 9),
(11, 'Akčný', 'Logan: Wolverine', '14.24', 2017, 'Wolverine (Hugh Jackman) se vrací. Jenže je na tom nyní trochu hůř. Jeho schopnost uzdravování pomalu vyprchává a elánem také zrovna nehýří. Navíc je na vše skoro sám. Z X-Menů přežívá ještě Charles Xavier známý také jako Profesor X (Patrick Stewart), který je ale vážně nemocný, ztrácí paměť a trpí nebezpečnými záchvaty ohrožujícími jeho okolí. Společně se ukrývají v opuštěné továrně na americko-mexické hranici. Jejich utajení ale skončí, když se objeví Laura (Dafne Keen), dívka, která má překvapivě stejné schopnosti jako Wolverine a v patách má navíc nelítostné pronásledovatele, kteří se jí snaží zmocnit. Ve chvíli, kdy Wolverine a Profesor X přijmou Lauru „do rodiny\", stávají se z nich štvanci, kterým jde po krku velmi brutální a vytrvalý nepřítel. Hrdinové na útěku mají k dispozici jen zbytky sil starých X-menů a Lauřiny schopnosti, které však ona sama těžko zvládá. A tak přichází čas, aby Wolverine v sobě našel zbývající vůli a sílu nejen k boji, ale i k tomu, aby Lauře předal své zkušenosti.', 10, 10),
(12, 'Dobrodružný', 'Stratený v džungli', '11.89', 2017, 'Mladý muž chce na cestách po světě uniknout rutinně a nudě západoevropského života. V bolívijské metropoli La Paz potkává nové parťáky z různých koutů světa a tajuplného průvodce. Ten je vezme na expedici do neprobádaných míst amazonského pralesa s tím, že mohou nalézt neznámý indiánský kmen, zcela nedotčenou přírodu a možná i naleziště zlata. Jenže uprostřed divočiny průvodce zmizí a skupina cestovatelů se při ztroskotání na divoké řece rozpadne. Hlavní hrdina Yossi zůstane uprostřed neprostupné, nehostinné a nebezpečné džungle sám. Bez nože či jiné zbraně, bez zásob a bez jakéhokoli přístřeší... úplně sám. Má sice za sebou tři roky vojenské služby, ale ty ho zdaleka nedokázaly připravit na všechno, co ho v dusném jihoamerickém pralese čeká. Krásná příroda se proměňuje v zelené peklo a v nepřítele plného útočných tvorů, jedovatých rostlin i hadů, odporného hmyzu a ohavných parazitů, jaké si ve středoevropských poměrech nedokážeme ani představit. Džungle má jasný vzkaz: sem lidé nepatří.', 3, 11),
(13, 'Dobrodružný', 'Besnenie', '11.39', 2018, 'Mezi samotářským primatologem Davisem Okoyem (Dwayne Johnson) a výjimečně inteligentním gorilím samcem Georgem, o kterého se Davis stará od jeho narození, vzniklo velmi pevné pouto. Nezdařený nebezpečný genetický experiment však změní toho mírného lidoopa v obrovské zuřící monstrum. A jako by to nestačilo, brzy se zjistí, že podobně jsou zmutována i další zvířata. Když se tito uměle vytvoření alfa predátoři nekontrolovatelně řítí Severní Amerikou a ničí vše, co jim přijde do cesty, Okoye začne ve spolupráci se zdiskreditovaným genetickým inženýrem vyvíjet protilátku a probíjí se nevyzpytatelným bojištěm, nejen aby zastavil hrozící celosvětovou katastrofu, ale také aby zachránil strašlivého netvora, který býval jeho přítelem.', 2, 12),
(14, 'Dobrodružný', 'Legenda o Tarzanovi', '5.95', 2016, 'Již mnoho let uplynulo od doby, kdy Tarzan (Alexander Skarsgård) zaměnil život v africké džungli za život bohatého Johna Claytona III, Lorda Greystoka, po boku své milované manželky Jane (Margot Robbie). Nyní je vyslán zpět do Konga jako obchodní emisar parlamentu, aniž by tušil, že má sehrát roli pěšáka ve smrtelně nebezpečné hře chamtivosti a pomsty belgického kapitána Leona Roma (Christoph Waltz). Ale lidé stojící za vražedným spiknutím vůbec netuší, s kým mají tu čest.', 10, 13),
(15, 'Dobrodružný', 'Poklad na Striebornom jazere', '14.24', 1962, 'Kdesi vysoko v horách je ukryto pohádkové bohatství - zlatý poklad, který po staletí střeží Tonkawové před chamtivými bělochy. A jak už to tak bývá, vždy se najde někdo, kdo lační po bohatství a nezastaví se před ničím. Takový je i Cornel a jeho banda trampů. Na scéně se ale včas objeví Vinnetou, Old Shatterhand a početná skupinka jejich přátel, takže je každému jasné, že na cestě za pokladem čeká všechny pořádná porce dobrodružství, romantiky, nebezpečí a motýlů. Tento dnes již vpravdě legendární film má celou řadu následovníků v podobě dalších mayovských adaptací, stál u zrodu několika hereckých hvězd, oplývá nádhernou jugoslávskou krajinou a v neposlední řadě dal řádnou injekci tehdejší německé kinematografii v podobě peněz i spokojených diváků.', 1, 14),
(16, 'Dobrodružný', ' Múmia', '18.04', 2017, 'Začněme v Egyptě před dvěma tisíci lety, kde se velmi ambiciózní princezna Ahmanet (Sofia Boutella) chystala na převzetí vlády v zemi po svém otci a pro naplnění svého cíle se neváhala spojit s temnými sílami a provádět věci, z nichž tuhla krev v žilách. Potrestali ji mumifikací zaživa a pohřbili tak, aby ji nikdo nenašel. Jenže našel. O dva tisíce let později se v místě jejího věčného odpočinku ocitli dobrodruh Nick Morton (Tom Cruise) a archeoložka Jenny Halsey (Annabell Wallis). Ti nešťastnou náhodou objevili Ahmanetin sarkofág, který nechala Jenny urychleně převézt do Londýna k dalšímu zkoumání. Jenny totiž pracuje pro tajnou organizaci Prodigium, jejímž posláním je pronásledování a odchyt těch nejnebezpečnějších monster. Ředitel Prodigia Dr. Jekyll (Russell Crowe) má v tomto směru poměrně bohaté zkušenosti. Jenže letadlo převážející mumii prokleté princezny až na místo určení nedoletí, ale zřítí se k zemi krátce před přistáním. Nickovi se jako zázrakem podaří katastrofu přežít, brzy ale zjistí, že smrt v troskách letadla by pro něj byla mnohem lepším řešením. Princezna Ahmanet se totiž díky jeho neuváženým činům probudila a touží po nadvládě nad světem. K tomu ale potřebuje i svého domnělého osvoboditele – Nicka.', 6, 15),
(17, 'Dobrodružný', 'Piráti Karibiku: 5', '20.95', 2017, 'V dalším pokračování svých fantastických dobrodružství se kapitán Jack, ke kterému se štěstěna opět jednou nemilosrdně obrátila zády, ocitá tváří v tvář bandě smrtících pirátských duchů pod vedením strašlivého kapitána Salazara (Javier Bardem), kterým se podařilo uniknout z Ďáblova trojúhelníku a jejichž jedinou touhou je připravit o život každého piráta - a zejména Jacka. Jackovou jedinou nadějí na přežití je bájný Poseidonův trojzubec, ale pokud má mít šanci ho nalézt, musí přesvědčit ke spolupráci Carinu Smythovou (Kaya Scodelario), geniální a krásnou astronomku, a Henryho (Brenton Thwaites), tvrdohlavého mladého námořníka a člena královského námořnictva. Jedině s jejich pomocí má kapitán Jack, svírající v rukách pevně kormidelní kolo Umírajícího racka, své zoufale nicotné a zchátralé lodi, naději nejen zvrátit nepřízeň osudu, se kterou se poslední dobou potýkal, ale také zachránit si život ve střetu s nejmocnějším a nejděsivějším protivníkem, jakému byl kdy nucen čelit.', 3, 16),
(18, 'Dobrodružný', 'Kong: Ostrov lebek', '11.49', 2017, 'Strhující původní dobrodružný film režiséra Jordana Vogt-Robertse vypráví příběh nesourodého týmu badatelů, vojáků a dobrodruhů, kteří se spojili, aby prozkoumali tajemný, stejně nebezpečný jako krásný, ostrov v kdesi v Pacifiku, který není zanesen do žádné mapy. Odříznuti od všeho, co znají, vstupují na území mohutného Konga a zažehávají tak nejstrašnější boj člověka s přírodou. Jejich cesta za poznáním se mění v boj o přežití a útěk z prapůvodního Ráje, ve kterém není pro člověka místo.', 1, 17),
(19, 'Dobrodružný', 'Robin Hood', '13.92', 2010, 'Britské ostrovy nebyly ve 13. století optimálním místem k životu. Už tak chudá země ještě financovala ambiciózní křížové výpravy svého krále Richarda. V řadách jeho vojsk hájil problematickou čest Anglické koruny i bezejmenný lučištník Robin (Russell Crowe). Ten se stane očitým svědkem smrti krále při obléhání francouzského hradu a spolu s několika kumpány se rozhodne na vlastní pěst dostat se po letech trmácení světem co nejrychleji domů, do Anglie. Ocitá se v hrabství Nottingham, které ovládá bezskrupulózní šerif (Matthew Mcfadyen). Málokdo se mu dokáže vzepřít, jednou z výjimek je Lady Marion (Cate Blanchett), která spravuje panství svého tchána (Max von Sydow), zatímco její muž bojuje za krále. Situace se ještě zhorší po Richardově smrti, když na trůn nastoupí slabý král Jan s dvorním našeptávačem Gisbornem (Mark Strong), který tajně osnuje francouzskou invazi do země. Ve chvíli nejvyšší nouze ale přichází doba hrdinů. Hrdinů jako je Robin. Muž, který se pokusí naplnit prázdné pojmy jako právo, spravedlnost a národní hrdost.', 7, 18),
(20, 'Múmia: Kolekcia', 'Múmia 1,2,3', '28.49', 1999, 'Vydajte sa v ústrety vzrušujúceho dobrodružstva, ktoré budete sledovať so zatajeným dychom a s napätím v očiach.\r\n\r\nBrandon Fraser sa predstavuje ako neohrozený Rick O\'Connell, bojovník proti všetkým nadprirodzeným hrozbám, bojovník, ktorý zvádza bitky s légiami nemŕtvych múmií naprieč celým svetom, či už je to rozpálená egyptská púšt, mrazivé Himaláje alebo Veľký čínsky múr!\r\n\r\nVychutnajte si celú trilógiu plnú smrtiacich nepriateľov, zoznámte sa s Dračím cisárom (Jet Li) i ďalšími desivými monštrami a užite si hrôzu naháňajúcu zábavu!', 4, 19),
(21, 'Dobrodružný', 'Everest', '10.11', 2015, 'Everest v režii Baltasara Kormákura rekapituluje jednu z nejtragičtějších expedic, při které majestátní masív poslal svým vyzyvatelům mrazivé varování. Píše se polovina devadesátých let a Himaláje se stávají oblíbenou turistickou destinací. Na osmitisícovky už nešplhají jen zkušení horolezci, ale táhnou se tam celá procesí dobrodruhů z celého světa. Horští vůdci Rob Hall (Jason Clarke) a Scott Fischer (Jake Gyllenhaal) přesto nic nepodceňují a do své expedice na nejvyšší bod naší Země berou jen lidi, kteří mají něco za sebou. Všichni jsou skvěle připravení a vybavení, splnění snů jejich klientů by nic nemělo stát v cestě. Stačí však drobná odchylka od plánu, náhlá změna počasí a klíčovou otázku „Podaří se nám horu zdolat?\" vystřídá otázka mnohem zásadnější. „Dokážeme přežít?\"', 4, 20),
(22, 'Romantický', 'Ja, Simon', '18.00', 2018, 'V šestnácti není snadné přiznat sobě a natož svému okolí, že jste gay. Simon Spier (Nick Robinson) začne po e-mailech flirtovat s neznámým spolužákem, který si říká Blue. Ale když se nešťastnou náhodou jejich korespondence dostane do cizích rukou, hrozí jim odhalení. Simona totiž začne vydírat jeho sociálně trochu podivný, ale jinak velmi sebejistý spolužák Martin (Logan Miller). Ten věří, že by mu Simon mohl domluvit rande s krásnou Abby (Alexandra Shipp). A pokud mu nepomůže… tak se jeho sexuální orientace stane věcí veřejnou. A co hůř, zveřejní i to, kdo se skrývá pod přezdívkou Blue. Simon se dostává do úzkých. Musí najít způsob, jak se z toho dostat dříve, než k tomu bude donucen.', 4, 21),
(23, 'Romantický', 'Päťdesiat odtieňov sivej', '8.95', 2015, 'Studentka literatury Anastasia (Dakota Johnson) je podle vlastních slov nezajímavá a nudná „šedá myš\" s nízkým sebevědomím, pravý opak tajemného podnikatele Christiana Greye (Jamie Dornan), kterého přišla vyzpovídat pro článek do studentského časopisu. Přestože se ji Grey svým chladným a odměřeným chováním snaží odradit, má ho plnou hlavu, což ještě prohloubí jejich opakovaná pracovní setkání. Bez ohledu na to, že ji varuje, jak je komplikovaný a ve zlověstných náznacích mluví o svém specifickém vkusu, není Anastasia jeho přitažlivosti schopná odolat. Ani Grey však není vůči téhle plaché dívce imunní a postupně ji začne otevírat dveře do své třinácté komnaty. Pokud do nich Anastasia vstoupí, pozná pravého Christiana Greye. Na posteli určené jen pro vyvolené zároveň pozná pravou Anastasii – své touhy, své vášně, svou živočišnost. Až z toho jde strach.', 9, 22),
(24, 'Romantický', 'Zimný príbeh', '10.99', 2014, 'V mýtickém prostředí New York City se více než jedno století odehrává příběh filmu „Winter\'s Tale\" plný zázraků, neblahých osudů a odvěkého konfliktu dobra a zla.', 6, 23),
(25, 'Romantický', 'Mandolína kapitána Corelliho', '5.06', 2001, 'Idylickou krásu řeckého pobřeží narušila válka. Italské okupační jednotky se vylodily na kdysi klidný ostrov Kefallénie. Kapitán Antonio Corelli (Nicolas Cage) se svým mužstvem bere svůj pobyt na ostrově jako dovolenou, s tím, že válka je na dosah vysílačky. Corelli, důstojník nezkrotné povahy, vášnivě miluje svoji mandolínu. Zpočátku odradí několik vesničanů. Zejména rozčilí vesnického lékaře Jannise (John Hurt) a jeho krásnou a vzdělanou dceru Pelagiu (Penélope Cruz), u nichž Corelli během okupace bydlí. Antonio si nakonec svým šarmem a slušným vystupováním a svou touhou, aby válka proběhla klidně, získá přes původní nenávist jejich přátelství. Když Pelagiin snoubenec, místní rybář Mandras (Christian Bale) odchází bojovat k partyzánům, vztah mezi Corellim a Pelagiou ještě zesílí. Jelikož se válka přiblíží, musí se milenci rozhodovat mezi loajálností vůči své vlasti a vzájemnou láskou - nezdolnou láskou, která musí překonat nepřízeň osudu a vydržet nevyhnutelné utrpení. Podle slavné literární předlohy Louise de Bernieres, která získala Cenu spisovatelů Britského společenství za nejlepší knihu roku 1995 euroasijského regionu.', 5, 24),
(26, 'Romantický', 'Hriešny tanec', '7.99', 1987, 'Frances Housemanová, přezdívaná Baby, tráví s rodiči léto v hotelu pro movitější hosty. Tady se dosud poslušná dcera seznámí nejen s divokým rytmem tance, který je konzervativními hosty považován za hříšný, ale také s tanečním instruktorem Johnnym Castlem. A když Johnnyho taneční partnerka Penny zjistí, že je v jiném stavu, a nemůže se zúčastnit vystoupení v sousedním hotelu, souhlasí Johnny, že místo ní zatančí s Baby. Začnou intenzivně trénovat a společné hodiny tance je natolik sblíží, že jejich vztah přeroste v lásku. Opravdovost citů však musí projít řadou těžkých zkoušek nejen na parketu, ale především v ovzduší konzervativní morálky, která jejich vztahu nepřeje.', 2, 25),
(27, 'Romantický', 'Pred úsvitom', '13.92', 1995, 'Vášnivá a inteligentní romance francouzské studentky a mladého Američana, kteří se potkají v rychlíku z Budapešti do Vídně. Čeká je neobyčejných čtrnáct hodin strávených neplánovanou expedicí po Vídni...', 6, 26),
(28, 'Romantický', 'Lásky čas', '7.89', 2013, 'Tim (Domhnall Gleeson) je naprosto obyčejný nesmělý jednadvacetiletý Brit, který má starostlivou matku, potrhlou sestru, úžasného otce (Bill Nighy) a žádnou holku. To se má brzy změnit, jelikož Tim právě dozrál do věku, kdy mu tatínek prozradí rodové tajemství. Všichni mužští členové tohoto rodu totiž mohou tak trochu cestovat v čase. „Tak trochu\" v tomto případě znamená, že se můžou vracet jen do minulosti, k událostem, které oni sami prožili. Stačí zajít do nějakého tmavého koutu, zavřít oči, sevřít pěsti a jste tam, kde jste si přáli být. Tim se okamžitě rozhodne využít téhle dovednosti k tomu nejdůležitějšímu, co člověk jeho věku potřebuje. Tedy k holce, pokud možno hezké, chytré, hodné a lačné po sexu. Ta Timova se jmenuje Mary (Rachel McAdams) a jejich vztah je dokonalý, protože všechny nedokonalosti Tim pokaždé napraví. Ovšem ani s takovou schopností nemůžete život obehrávat donekonečna, zvlášť když je to prevít, který vám připravuje jedno nelehké dilema za druhým. S každým návratem totiž přijdete o všechno, co jste do té doby prožili. A to někdy hodně mrzí.', 1, 27),
(29, 'Romantický', 'Navždy a ďaleko', '13.92', 1992, 'Hrdiny jsou chudý irský rolník Joseph Donelly a dcera bohatého irského statkáře Shannon Christie, které se příčilo žít jako bohatá anglická dáma svázaná stovkami zákazů, příkazů a omezení. Společně koncem minulého století přichází do Ameriky, aby se jako stovky dalších pokusili získat kus vlastní půdy. Růžové sny o zemi zaslíbené se však velmi rychle roztříští o drsnou realitu. Dvojice musí žít v nuzných podmínkách a tvrdou prací si vydělávat na živobytí i cestu do Oklahomy, kde ještě lze získat půdu. Zažívají krátké okamžiky štěstí i hořkých proher a přestože se jeden druhému líbí, stále k sobě nemohou najít cestu. A jako by to nestačilo, je Shannon jedné zimní noci postřelena.', 3, 28),
(30, 'Romantický', 'Hra snov', '6.69', 1999, 'Legendární nadhazovač Detroitských Tigrů, Billy Chapel, byl vždycky lepší v baseballu než v lásce. Po strašné sezóně, která by mohla být koncem jeho kariéry, mu přítelkyně Jane (Kelly Preston) oznámí, že odchází. Billyho kariéra i láska jsou na hraně a on musí znovu dokázat co v něm je. Každým nadhozem se dostává blíž k nejdůležitějšímu rozhodnutí svého života.', 1, 29),
(31, 'Romantický', ' Twilight sága: Úsvit - 2. čast', '6.99', 2012, 'Závěrečná část světoznámé upírské ságy nás naposledy zavede do světa, kde upíři a vlkodlaci bojují nejen o svou lásku, ale i o vlastní životy. Novorozená upírka Bella a její manžel Edward mohou být konečně navždy spolu a šťastní, ale příchod jejich pozoruhodné dcery Renesmee uvede do pohybu nebezpečný řetězec událostí, které pro ně mohou skončit katastrofou. Rodina Cullenových se ale rozhodne bojovat a kontaktuje přátele z celého světa, aby spojili své síly a postavili se vládnoucímu rodu Volturiových. Velkolepá bitva, kde vítězství může vše změnit, právě začíná. Napínavé a romantické pokračování filmu Rozbřesk vám připomene proč se Twilight sága stala fenoménem a ukradla srdce dívkám a ženám po celém světě.', 8, 30),
(32, 'Scifi', 'Solo: A Star Wars Story', '19.90', 2018, 'Naloďte se na Millennium Falcon a vydejte se do předaleké galaxie ve filmu Solo: Star Wars Story, zbrusu novém dobrodružství nejoblíbenějšího syčáka v galaxii. V řadě troufalých eskapád hluboko v temném a nebezpečném zločineckém podsvětí potkává Han Solo nejen mohutného Chewbaccu, svého budoucího kopilota, ale narazí i na nechvalně známého hazardního hráče Landa Calrissiana. Na této cestě se zrodí jeden z nejnepravděpodobnějších hrdinů ságy Star Wars.', 15, 31),
(33, 'Scifi', 'Pacific Rim: Povstanie', '17.95', 2018, 'Poprvé jsme je dokázali zastavit. Jenže to, co mimozemští tvorové Kaiju napáchali na Zemi v prvním díle akčního sci-fi Pacific Rim byla jen předehra k tomu, co si pro lidstvo připravili teď. Hvězda Star Wars John Boyega a Scott Eastwood z Rychle a zběsile vedou tým, který je poslední nadějí na přežití planety. Členy tohoto týmu jsou piloti ovládající Jaegery, obří roboty, kteří jsou svou velikostí a vybavením schopní konkurovat stejně vybaveným Kaiju. Jake Pentecost (John Boyega) k nim dlouhou patřil, jenže pak se vykašlal na svůj talent i na odkaz svého otce, jenž v boji proti Kaiju obětoval vlastní život. Raději přežívá v ilegalitě a na živobytí si vydělává nejrůznějšími aktivitami za hranou zákona. Při jedné takové akci narazí na patnáctiletou Amaru, která dokázala ukrást a rozchodit původně k likvidaci určeného Jaegera. Než se tihle dva stačí pořádně seznámit, mají v patách Zákon. Aby unikli trestu, začlení se do programu výcviku nových pilotů Jaegerů. Jake po boku svého bývalého parťáka Lamberta (Scott Eastwood) jako instruktor a Amara jako nadějná pilotka. Všichni doufají, že si tréninkové schopnosti nikdy nebudou muset vyzkoušet v reálné válce. Jenže ta přichází. Dřív, než si všichni přáli, a ze směru, odkud ji nikdo nečekal.', 8, 32),
(34, 'Scifi', 'Ant-Man a Wasp', '20.95', 2018, 'Filmový svět studia Marvel se rozrůstá o snímek Ant-Man a Wasp, který je novou kapitolou o superhrdinech, kteří se umějí zmenšovat. Po událostech filmu Captain America: Občanská válka musí Scott Lang čelit následkům svých rozhodnutí nejen jako superhrdina, ale i otec. Sotva se mu podaří najít rovnováhu mezi osobním životem a povinnostmi, které má jako Ant-Man, objeví se Hope van Dyneová a dr. Hank Pym s novou naléhavou misí. Scott musí znovu obléci zmenšovací oblek, naučit se bojovat po boku Wasp a pomoci jí odhalit tajemství z minulosti.', 3, 33),
(35, 'Scifi', '7 sestier', '14.90', 2017, 'Sedm životů, sedm sester, jedna společná identita. Originální akční sci-fi thriller o sedmi identických sestrách, které tají svou existenci před okolním světem. Dokud jedna z nich nezmizí. Přelidněný svět roku 2073 se řídí drastickým zákonem jednoho dítěte na rodinu. Pokud úřady objeví přestupek, mladší sourozenec je nesmlouvavě odebrán. V jednom bytě se ale už třicet let skrývá a žije sedm sester. Vypadají stejně, přesto je každá jiná a každá je svá. Všechny dohromady pak mají jednu identitu pro pohyb venku, kde vystupují jako jedna osoba a žijí jeden společný oficiální život. Chodí do školy, do práce, s kolegy do baru, vztahy pouze na jednu noc. Každá ze sester chodí ven jeden den v týdnu. Pondělí vychází v pondělí, Úterý v úterý a tak dále až je řada na Neděli. Jejich systém funguje po mnoho let skvěle. Až do toho dne, kdy se Pondělí nevrátí domů. Šest zbylých sester musí opustit svůj úkryt a zjistit, co se stalo. Jakákoliv chyba je ale může prozradit a jejich život se z pevného klidného řádu mění v napínavou futuristickou akci plnou adrenalinu a nečekaných momentů.', 8, 34),
(36, 'Scifi', 'Star Wars: Poslední Jediovia', '22.94', 2017, 'Ve filmu Star Wars: Poslední z Jediů od studia Lucasfilm pokračuje sága rodu Skywalkerů. Postavy předchozího filmu Star Wars: Síla se probouzí spolu s legendárními hrdiny galaxie prožívají strhující dobrodružství, během kterých odhalí prastará tajemství Síly a šokující události z minulosti.', 2, 35),
(37, 'Scifi', 'Vojna o planétu opíc', '23.99', 2017, 'Válka o planetu opic začíná dva roky po událostech předchozího snímku Úsvit planety opic. Z inteligentního šimpanze Caesara (Andy Serkis) se stal nezpochybnitelný vůdce rozrůstajícího se společenství opic, a když se s ním nyní setkáváme, je mu okolnostmi vnucena nová role válečného generála. Situace opičího klanu vedeného Caesarem je totiž katastrofální. Jejich skupina ustoupila do lesů, kde se často utkávají v bitvách s lidskou armádou, vedenou nelítostným plukovníkem McCulloughem (Woody Harrelson). Ztráty opičího společenství jsou obrovské a Caesar cítí bolest z každé smrti. Potýká se s vlastními temnějšími instinkty a nastupuje na cestu pomsty, na níž se nevyhnutelně střetne s plukovníkem v epické bitvě, která určí, kdo se stane vůdčím druhem, jenž bude určovat další osud těch druhých, poražených.', 1, 36),
(38, 'Scifi', 'X-Men: Budúca minulosť', '4.99', 2014, 'Zmutovaným hrdinům X-Men hrozí definitivní zánik. Jejich rasa byla vždy na pokraji vyhynutí, ale teď je ta hrozba ještě reálnější než kdy jindy. Jediná cesta ke spasení vede přes minulost, na samý začátek řetězce událostí, které stávající nebezpečí vyvolaly. K bytostem s výjimečnými schopnostmi se vrací režisér Bryan Singer, strůjce jejich mimořádného úspěchu. Spolu s ním ve filmu X-Men: Budoucí minulost přichází i nejvíc mutantů v historii této ságy. Díky tomu, že se film odehrává ve dvou časových rovinách, objeví se v něm hned dvě podoby vůdce „hodných\" X-Men, profesora Xaviera (Patrick Stewart, James MacAvoy) a jeho protivníka Magneta (Ian McKellen, Michael Fassbender). Pouze Wolverine (Hugh Jackman) zůstává stále stejný díky schopnosti nestárnout a bleskurychle se uzdravovat. Právě on proto dostane zdánlivě šílený úkol, vrátit se v čase a zabránit tomu, aby se z bývalých přátel stali soupeři na život a na smrt. Jedině spolu totiž mohou v budoucnosti čelit síle, která předčí i jejich unikátní schopnosti.', 10, 37),
(39, 'Scifi', 'Transformers: Zánik', '12.95', 2014, 'Automechanik Cade Yager (Walhberg) se snaží uživit sebe a svou dospívající dceru Tessu (Nicola Peltz) opravováním hodně nepojízdných vraků. Zoufale se mu nedaří, ale jen do doby, než se z jednoho roztřískaného náklaďáku vyklube Transformer a zrovna ten nejdůležitější – Optimus Prime. Cade z toho jen těžko může mít radost, protože Amerika se ještě úplně nevzpamatovala ze souboje „hodných\" Autobotů se „zlými\" Deceptikony, který na konci třetího dílu zlikvidoval půlku Chicaga. Čtyři roky poté jsou všichni zástupci téhle mimozemské rasy na indexu a elitní vědecké mozky se snaží vytvořit pozemské Transformery, kteří by účinněji čelili podobným hrozbám. Z minulosti ale víme, že cesta do pekel bývá dlážděná dobrými úmysly, a jinak tomu nebude ani v tomto případě. To však Cadea příliš netrápí. Zatím. Jako nový lidský parťák toho nejslavnějšího z Transformerů se ocitl nejen v hledáčku americké vlády, ale pronásledují ho i Optimovi krajané. Do toho všeho se jeho dcera zamilovala, s čímž jako otec rozhodně nemůže souhlasit. Čtvrtí Transformers kromě Wahlberga v hlavní roli přinesou ještě jednu zásadní novinku – Dinoboty, což jsou mechaničtí tvorové, kteří vypadají jako prehistoričtí ještěři. Vítejte v transformovaném Jurském parku.', 9, 38),
(40, 'Scifi', 'Votrelec: Covenant', '14.99', 2017, 'Snímkem Vetřelec: Covenant se režisér Ridley Scott vrací do vesmíru, který sám stvořil ve Vetřelci, prvním filmu věnovaném nejstrašnějšímu mimozemskému monstru filmové historie. V nejnovější a ještě děsivější kapitole se připravuje posádka vesmírné lodi Covenant kolonizovat vzdálenou planetu na druhé straně galaxie. Nový svět, který nečekaně objeví, se jim z počátku zdá být dosud nezmapovaným idylickým rájem. Ve skutečnosti je to ale temný a brutální svět, jehož hrůzy si nikdo z členů posádky nedokázal představit ani v těch nejhorších představách. Když se tito vesmírní poutníci ocitnou tváří v tvář smrtícímu monstru, nezbývá jim nic jiného než se aspoň pokusit o zoufalý únik z tohoto zdánlivého ráje proměněného ve skutečné peklo.', 2, 39),
(41, 'Scifi', 'Strážcovia Galaxie', '14.95', 2014, 'V tomto akcí nabitém, výpravném vesmírném dobrodružství se odvážný dobrodruh Peter Quill stává středem zájmu nájemných zabijáků poté, co Ronanovi, mocnému padouchovi s plány ohrožující celý vesmír, ukradne tajemnou kouli. Aby neúnavnému Ronanovi unikl, je Quill nucen spojit své síly se čtveřicí pozoruhodných hrdinů – Rocketem, po zuby ozbrojeným mývalem, Grootem, humanoidem, který připomíná strom, vražednou a tajemnou Gamorou a pomstychtivým Draxem Ničitelem. Když ale Quill objeví skutečnou moc koule a hrozbu, která se v ní ukrývá a ohrožuje celý vesmír, musí udělat vše pro to, aby nesourodá skupina táhla za jeden provaz a v posledním zoufalém souboji se pokusila zachránit osud celé galaxie.', 6, 40),
(42, 'Vojnový', 'Zachráňte vojaka Ryana', '25.49', 1998, 'Druhá světová válka byla rozhodující událostí 20. století a pro Ameriku se stala určujícím dějinným zvratem. Změnila tehdy hranice světa a dnes je nazývána \"poslední velkou válkou\". Ani sebelepší výcvik však nemohl spojenecké vojáky připravit na to, co ječekalo po vylodění v Normandii, na pláži s krycím jménem Omaha. Přestože byli naplněni odhodláním a vírou ve vítězství, jen málokdo z nich bitvu o tento malý kus francouzského pobřeží přežil. Z pohledu kapitána Johna Millera je zřejmé, že si uvědomuje nebezpečí, které na jeho jednotku čeká. Netuší však, že to není zdaleka ten nejtěžší úkol, který bude muset se svými vojáky splnit...', 2, 41),
(43, 'Horor', 'To', '28.95', 2017, 'Když ve městě Derry ve státě Maine začnou mizet děti, musí skupina mladých chlapců a děvčat čelit svým největším obavám v boji proti zlému klaunovi jménem Pennywise, jehož vražedná a násilnická historie se táhne napříč staletími.', 4, 42),
(44, 'Dobrodružný', 'Revenant Zmŕtvychvstanie', '13.92', 2015, 'Americký západ, Jižní Dakota, 1823. Místo a čas s hodně relativní hodnotou lidského života. Zkušený lovec a trapper Hugh Glass (Leonardo DiCaprio) je se svým synem na výpravě s lovci kožešin. Uprostřed hlubokých lesů vzdorují nečekaným útokům indiánů a musí na své pouti překonávat nemilosrdnou, zatím nezmapovanou krajinu plnou nástrah. Glassovi se stává osudným střet s rozzuřenou samicí medvěda grizzlyho. Medvědí útok sice přežije, ale je těžce zraněný a lovecká výprava se musí rozdělit. Zatímco většina lovců pokračuje v cestě, s Glassem a jeho synem zůstanou jen dva muži, John Fitzgerald (Tom Hardy) a Jim Bridger (Will Poulter). Ti více méně jen čekají, až zemře, aby jej pak pohřbili a mohli pokračovat v cestě. Ale zraněný lovec stále neumírá, a tak se Fitzgerald rozhodne čekání na nevyhnutelné zkrátit. Při pokusu o nedobrovolnou eutanázii ho však přistihne Glassův syn, kterého Fitzgerald zabije. Ještě živého Glasse pak zahrabe v hrobě a spolu s Bridgerem zmizí. Jenže Hugh má hodně tuhý kořínek. V naprosto zuboženém stavu vyleze z vlastního hrobu, zoufale se potácí čarokrásnou, ale zcela lhostejnou krajinou. Při životě jej drží především nenávist a touha po odplatě. Musí překonat brutální zimu a hlad, divoké řeky, bojovné indiánské kmeny a dokonat svou pomstu.', 3, 43),
(45, 'Mysteriózny', 'Prekliaty ostrov', '29.74', 2010, 'Detektiva Teddyho Danielse (Di Caprio) a jeho kolegu Chucka Auleho (Mark Ruffalo) přivedlo na prokletý ostrov Shutter pátrání po šílené vražedkyni jménem Rachel Solando (Emily Mortimer), která zmizela ze své cely ve vězeňské psychiatrické léčebně Ashecliffe a kdesi se úspěšně skrývá. Píše se rok 1954 a Amerika se dosud nevzpamatovala z následků Druhé světové války a navíc přežívá v permanentní paranoii domnělého i skutečného komunistického ohrožení. Daniels je učebnicovou obětí téhle doby. Válečný veterán stále vzpomíná na prožité hrůzy a navíc se musí vyrovnat se smrtí manželky. Až by se dalo sarkasticky říct, že v rámci vyšetřování dorazil na správné místo. Jenže na tomhle ostrově něco smrdí a zkušený detektiv to instinktivně vycítí. Například je přesvědčený o tom, že léčebné metody, které zdejší lékaři vedení doktorem Johnem Cawleym (Ben Kingsley) aplikují na pacienty, nejsou zcela v souladu s Hippokratovou přísahou. Druhou stranou mince je ale otázka detektivovy příčetnosti, jež je vlivem traumatických prožitků z minulosti a poměrně děsivé a skličující přítomnosti vystavována čím dál větším otřesům.', 1, 44),
(46, 'Drama', 'Červená volavka', '18.14', 2018, 'Baletky, které musí předčasně ukončit svou kariéru, to nemají jednoduché. Celý svůj život do té chvíle věnovaly jen tanci a jejich příprava na skutečný život není dokonalá. Až na maximální sebekázeň a vůli dohnanou až do krajnosti. Bývalá primabalerína Dominika Jegorovová (Jennifer Lawrence) navíc žije v dnešním Rusku a se svou matkou čelí bezútěšné a nejisté budoucnosti. Díky tomu se stává snadnou kořistí ruské tajné zpravodajské služby a dostává se do jejího kurzu, v němž školí „volavky“. Zde probíhá tvrdý výcvik, jehož cílem je naučit své „žákyně“, aby v roli profesionálních svůdnic využívaly své tělo a mysl jako dokonalé zbraně. Po ukončení zvráceného a sadistického tréninku je Dominika jako nejnebezpečnější volavka nasazena na Nathaniela Nashe (Joel Edgerton), důstojníka CIA, který řídí jednoho z nejdůležitějších špiónů v Rusku. Dominika s Nathanielem vede souboj silných vůlí plný špionských triků, nedůvěry, ale především vnitřně bojují s nevyhnutelnou vzájemnou touhou. Dokáže ji Nathaniel přesvědčit, že je právě on tou jedinou osobou, které může věřit?', 7, 45),
(47, 'Akčný', 'RAMBO 1-3 Kolekcia', '28.49', 2017, 'Filmy o elitním vojákovi Johnu Rambovi jsou skutečně kultovní, proto vychází tato kolekce prvních tří filmů, ve kterých exceluje Sylvester Stallone jako John Rambo. Najdete zde první film, kdy se mladý veterán vrací z války z Vietnamu, ale není schopen začlenit se do společnosti. Ve druhém filmu se vrací do Vietnamu osvobodit zajaté Američany. Ve třetím potom musí zachránit plukovníka Trautmana, který byl unesen ruským plukovníkem v Afghánistánu.', 2, 46),
(48, 'Akčný', 'Jason Bourne', '25.00', 2016, 'Jason Bourne (Matt Damon) už poskládal skoro všechny střípky své rozbité životní mozaiky. Potrestal většinu tvůrců zvláštního programu, který z něj udělal stroj na zabíjení. Chce hodit minulost za hlavu a dál pokračovat prostou přítomností, kterou představují ilegální boxerské zápasy. Z tohohle komfortu ho vytrhne bývalá kolegyně, zběhlá agentka Nicky (Julia Stiles), která mu připomene, že na ty nejpalčivější otázky ještě odpovědi nedostal. Když ho pak málem dostane nájemný zabiják, pustí se znovu do boje s Agenturou, teď reprezentovanou tvrdým ředitelem Robertem Deweym (Tommy Lee Jones) a jednou nebezpečně chytrou analytičkou (Alicia Vikander). Jason Bourne se ocitá na staré známé horké půdě, kde nemůže věřit nikomu a ničemu a kde přežití vyžaduje, aby si vzpomněl na to, co se naučil v programu, který díky němu skončil.', 8, 47),
(49, 'Scifi', 'Matrix', '13.94', 1999, 'Uvěříte neuvěřitelnému! Představte si, že vaše realita je jen iluzí a vaše nejtemnější noční můry jsou ve skutečnosti pravdivé. Představte si, že vaše současnost je vlastně minulostí a to budoucí se děje právě teď. Když si to dokážete představit, potom se budete cítit jako hrdina snímku Matrix Thomas Anderson (Keanu Reeves). A věřte, že to nebude příjemný pocit. Anderson je normální mladý muž, který se jen snaží přežít v každodenním shonu moderního velkoměsta. A má všechny předpoklady aby se mu to povedlo: dobré přátele, milující rodinu a perspektivní práci v multinárodní počítačové společnosti Meta Cortech. Jednoho dne, nebo lépe řečeno noci, se však do jeho spokojeného mozku zakousne strašlivá noční můra. Zdá se mu, že byl proti své vůli vložen v podobě dat do počítače a všechno to, co až dosud považoval za svůj osud, je jen vírem dat okolo několika tištěných spojů. Má pocit, že mu byla jeho mysl ukradena a uvězněna v obřím Matrix počítače budoucnosti. Začíná vážně pochybovat o své každodenní skutečnosti. Byl skutečně vhozen do stroje? Kdo je za to zodpovědný? Je tam s ním zavřeno i těch několik stovek lidí, které zná? Nebo jsou to jen projekce, které mají udržet zdání reality? A pak je tu otázka nejdůležitější: pokud je to všechno pravda, co se stane, až jeho věznitelé přijdou na to, že ji zná?', 1, 48),
(50, 'Horor', 'Tiché miesto', '18.04', 2018, 'Lee (John Krasinski) a Evelyn (jeho životní partnerka Emily Blunt) Abbottovi vychovávají tři děti. Všichni jsou zatím naživu. Velmi rychle si totiž osvojili pravidla, která začala platit po Jejich příchodu na Zemi. Kdo jsou ti Oni? Nikdo neví. Ví se jen to, že mají mimořádně vyvinutý sluch a každičký zvuk přiláká jejich pozornost. A jejich pozornost pro lidi znamená jistou smrt, což záhy na vlastní kůži poznají i Abbottovi. Ti dosud jako jedni z mála přežívali i díky tomu, že je jejich nejstarší dcera Regan neslyšící, a tak pro ně byla znalost znakové řeči absolutní nutností i v „normálních dobách“. Kromě toho vyvinuli na odlehlé farmě, kde žijí, celou řadu bezpečnostních opatření, jež je mají chránit, počínaje zvukově izolovaným sklepem a konče molitanem obalenými kostkami k Monopolům. Bude to ale k bezpečí stačit? Takový život totiž připomíná tanec v minovém poli a čekání na jednu jedinou, leč osudovou chybu. Evelyn je navíc těhotná a termín porodu se kvapem blíží. A některé životní události se bez křiku jednoduše neobejdou.', 13, 49),
(51, 'Akčný', 'Predátor', '32.29', 1987, 'V džungli přistane kosmická loď, na jejíž palubě je dokonale vybavený mimozemský nimrod. Lovnou zvěří se pro něj stávají nejen dravci obývající džungli, ale také lidé. To je prolog slavného filmu, který je oblíbenou žánrovou kombinací akčních příběhů o amerických komandos, hororu a SF. Oddíl pod vedením zkušeného majora Dutche Schaefera je vysazen na nepřátelském území, kde má uprostřed džungle vysvobodit několik amerických vojáků ze zajetí partyzánů. Po úspěšně provedené akci se však američtí vojáci musí utkat s daleko tajemnějším a nebezpečnějším nepřítelem. Džungle se mění v past, z níž není úniku a američtí hrdinové poprvé v životě poznávají, co je to strach. Film, který dnes již bývá řazen ke klasice žánru, zaujme především napětím a houstnoucí atmosférou strachu, kdy jsou američtí supermani pomalu vyváděni z rutinní statečnosti a rovnováhy. Stejně zdařilé je i pojetí mimozemšťana, neostré, děsivě tajuplné postavy, využívající dokonalé mimikry, jehož přítomnost signalizuje pouze termografie jeho pohledu. Teprve v závěrečné scéně se na scéně objevují v celé hrůznosti dokonalé masky Stana Winstona.', 2, 50);

--
-- Kľúče pre exportované tabuľky
--

--
-- Indexy pre tabuľku `film`
--
ALTER TABLE `film`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `obrazok` (`obrazok`);

--
-- AUTO_INCREMENT pre exportované tabuľky
--

--
-- AUTO_INCREMENT pre tabuľku `film`
--
ALTER TABLE `film`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=52;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
